"""Initial schema

Revision ID: 2632e6a0757e
Revises: 
Create Date: 2026-07-02 11:57:52.489278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2632e6a0757e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('recruiter_name', sa.String(), nullable=True),
    sa.Column('recruiter_email', sa.String(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=True),
    sa.Column('gmail_thread_id', sa.String(), nullable=True),
    sa.Column('gmail_link', sa.String(), nullable=True),
    sa.Column('application_source', sa.String(), nullable=True),
    sa.Column('resume_used', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_email_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_company'), 'applications', ['company'], unique=False)
    op.create_index(op.f('ix_applications_gmail_message_id'), 'applications', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_applications_is_active'), 'applications', ['is_active'], unique=False)
    op.create_index(op.f('ix_applications_role'), 'applications', ['role'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('email_subject', sa.String(), nullable=True),
    sa.Column('email_date', sa.DateTime(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=True),
    sa.Column('llm_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_application_id'), 'status_history', ['application_id'], unique=False)
    op.create_index(op.f('ix_status_history_gmail_message_id'), 'status_history', ['gmail_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_gmail_message_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_application_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_role'), table_name='applications')
    op.drop_index(op.f('ix_applications_is_active'), table_name='applications')
    op.drop_index(op.f('ix_applications_gmail_message_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_company'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
