"""Add raw email sync state processing runs and enums

Revision ID: b007e65069e2
Revises: 2632e6a0757e
Create Date: 2026-07-02 12:01:53.860515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b007e65069e2'
down_revision: Union[str, Sequence[str], None] = '2632e6a0757e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_sync_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_history_id', sa.String(), nullable=True),
    sa.Column('last_sync_time', sa.DateTime(), nullable=False),
    sa.Column('last_processed_message_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('emails_scanned', sa.Integer(), nullable=False),
    sa.Column('emails_processed', sa.Integer(), nullable=False),
    sa.Column('new_applications', sa.Integer(), nullable=False),
    sa.Column('updated_applications', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_emails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_emails_classification'), 'raw_emails', ['classification'], unique=False)
    op.create_index(op.f('ix_raw_emails_message_id'), 'raw_emails', ['message_id'], unique=True)
    op.create_index(op.f('ix_raw_emails_processed'), 'raw_emails', ['processed'], unique=False)
    op.create_index(op.f('ix_raw_emails_thread_id'), 'raw_emails', ['thread_id'], unique=False)
    op.add_column('applications', sa.Column('company_confidence', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('role_confidence', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('status_confidence', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('overall_confidence', sa.Float(), nullable=True))
    op.add_column('status_history', sa.Column('status_confidence', sa.Float(), nullable=True))
    op.add_column('status_history', sa.Column('overall_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status_history', 'overall_confidence')
    op.drop_column('status_history', 'status_confidence')
    op.drop_column('applications', 'overall_confidence')
    op.drop_column('applications', 'status_confidence')
    op.drop_column('applications', 'role_confidence')
    op.drop_column('applications', 'company_confidence')
    op.drop_index(op.f('ix_raw_emails_thread_id'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_processed'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_message_id'), table_name='raw_emails')
    op.drop_index(op.f('ix_raw_emails_classification'), table_name='raw_emails')
    op.drop_table('raw_emails')
    op.drop_table('processing_runs')
    op.drop_table('gmail_sync_state')
    # ### end Alembic commands ###
