"""Add review and cost columns

Revision ID: c9c8b7e3fe09
Revises: cb36d89e71cf
Create Date: 2026-07-02 12:10:09.926638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c8b7e3fe09'
down_revision: Union[str, Sequence[str], None] = 'cb36d89e71cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('needs_review', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_applications_needs_review'), 'applications', ['needs_review'], unique=False)
    op.add_column('processing_runs', sa.Column('input_tokens', sa.Integer(), nullable=False))
    op.add_column('processing_runs', sa.Column('output_tokens', sa.Integer(), nullable=False))
    op.add_column('processing_runs', sa.Column('cost_usd', sa.Float(), nullable=False))
    op.add_column('raw_emails', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('status_history', sa.Column('needs_review', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_status_history_needs_review'), 'status_history', ['needs_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_needs_review'), table_name='status_history')
    op.drop_column('status_history', 'needs_review')
    op.drop_column('raw_emails', 'retry_count')
    op.drop_column('processing_runs', 'cost_usd')
    op.drop_column('processing_runs', 'output_tokens')
    op.drop_column('processing_runs', 'input_tokens')
    op.drop_index(op.f('ix_applications_needs_review'), table_name='applications')
    op.drop_column('applications', 'needs_review')
    # ### end Alembic commands ###
