"""Add processing_state to raw_emails

Revision ID: cb36d89e71cf
Revises: b007e65069e2
Create Date: 2026-07-02 12:05:05.799145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb36d89e71cf'
down_revision: Union[str, Sequence[str], None] = 'b007e65069e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_emails', sa.Column('processing_state', sa.String(), nullable=False))
    op.add_column('raw_emails', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('raw_emails', sa.Column('raw_llm_json', sa.Text(), nullable=True))
    op.add_column('raw_emails', sa.Column('prompt_version', sa.String(), nullable=True))
    op.add_column('raw_emails', sa.Column('model', sa.String(), nullable=True))
    op.add_column('raw_emails', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('raw_emails', sa.Column('token_usage', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_raw_emails_processed'), table_name='raw_emails')
    op.create_index(op.f('ix_raw_emails_processing_state'), 'raw_emails', ['processing_state'], unique=False)
    op.drop_column('raw_emails', 'processed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_emails', sa.Column('processed', sa.BOOLEAN(), nullable=False))
    op.drop_index(op.f('ix_raw_emails_processing_state'), table_name='raw_emails')
    op.create_index(op.f('ix_raw_emails_processed'), 'raw_emails', ['processed'], unique=False)
    op.drop_column('raw_emails', 'token_usage')
    op.drop_column('raw_emails', 'temperature')
    op.drop_column('raw_emails', 'model')
    op.drop_column('raw_emails', 'prompt_version')
    op.drop_column('raw_emails', 'raw_llm_json')
    op.drop_column('raw_emails', 'error_message')
    op.drop_column('raw_emails', 'processing_state')
    # ### end Alembic commands ###
